//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.269
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapsFlashInWpf.Services {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Node", Namespace="http://schemas.datacontract.org/2004/07/DBComponent")]
    [System.SerializableAttribute()]
    public partial class Node : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double lonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int priorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int zoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lat {
            get {
                return this.latField;
            }
            set {
                if ((this.latField.Equals(value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lon {
            get {
                return this.lonField;
            }
            set {
                if ((this.lonField.Equals(value) != true)) {
                    this.lonField = value;
                    this.RaisePropertyChanged("lon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prior {
            get {
                return this.priorField;
            }
            set {
                if ((this.priorField.Equals(value) != true)) {
                    this.priorField = value;
                    this.RaisePropertyChanged("prior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int zone {
            get {
                return this.zoneField;
            }
            set {
                if ((this.zoneField.Equals(value) != true)) {
                    this.zoneField = value;
                    this.RaisePropertyChanged("zone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReadingFromConfigFault", Namespace="http://Microsoft.ServiceModel.Samples")]
    [System.SerializableAttribute()]
    public partial class ReadingFromConfigFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Problem_HelpLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Problem_messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GoogleMapsFlashInWpf.Services.Node[] RightPathesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WrongNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Problem_HelpLink {
            get {
                return this.Problem_HelpLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.Problem_HelpLinkField, value) != true)) {
                    this.Problem_HelpLinkField = value;
                    this.RaisePropertyChanged("Problem_HelpLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Problem_message {
            get {
                return this.Problem_messageField;
            }
            set {
                if ((object.ReferenceEquals(this.Problem_messageField, value) != true)) {
                    this.Problem_messageField = value;
                    this.RaisePropertyChanged("Problem_message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GoogleMapsFlashInWpf.Services.Node[] RightPathes {
            get {
                return this.RightPathesField;
            }
            set {
                if ((object.ReferenceEquals(this.RightPathesField, value) != true)) {
                    this.RightPathesField = value;
                    this.RaisePropertyChanged("RightPathes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WrongName {
            get {
                return this.WrongNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WrongNameField, value) != true)) {
                    this.WrongNameField = value;
                    this.RaisePropertyChanged("WrongName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="Services.IAlgorithmServer")]
    public interface IAlgorithmServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlgorithmServer/getShortestPath", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlgorithmServer/getShortestPathResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GoogleMapsFlashInWpf.Services.ReadingFromConfigFault), Action="http://Microsoft.ServiceModel.Samples/IAlgorithmServer/getShortestPathReadingFrom" +
            "ConfigFaultFault", Name="ReadingFromConfigFault")]
        GoogleMapsFlashInWpf.Services.Node[] getShortestPath(GoogleMapsFlashInWpf.Services.Node start, GoogleMapsFlashInWpf.Services.Node finish);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlgorithmServerChannel : GoogleMapsFlashInWpf.Services.IAlgorithmServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlgorithmServerClient : System.ServiceModel.ClientBase<GoogleMapsFlashInWpf.Services.IAlgorithmServer>, GoogleMapsFlashInWpf.Services.IAlgorithmServer {
        
        public AlgorithmServerClient() {
        }
        
        public AlgorithmServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlgorithmServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlgorithmServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlgorithmServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GoogleMapsFlashInWpf.Services.Node[] getShortestPath(GoogleMapsFlashInWpf.Services.Node start, GoogleMapsFlashInWpf.Services.Node finish) {
            return base.Channel.getShortestPath(start, finish);
        }
    }
}
