//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapsFlashInWpf.Database {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Node", Namespace="http://schemas.datacontract.org/2004/07/DBComponent")]
    [System.SerializableAttribute()]
    public partial class Node : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double lonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int priorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int zoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lat {
            get {
                return this.latField;
            }
            set {
                if ((this.latField.Equals(value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lon {
            get {
                return this.lonField;
            }
            set {
                if ((this.lonField.Equals(value) != true)) {
                    this.lonField = value;
                    this.RaisePropertyChanged("lon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prior {
            get {
                return this.priorField;
            }
            set {
                if ((this.priorField.Equals(value) != true)) {
                    this.priorField = value;
                    this.RaisePropertyChanged("prior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int zone {
            get {
                return this.zoneField;
            }
            set {
                if ((this.zoneField.Equals(value) != true)) {
                    this.zoneField = value;
                    this.RaisePropertyChanged("zone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Street", Namespace="http://schemas.datacontract.org/2004/07/DBComponent")]
    [System.SerializableAttribute()]
    public partial class Street : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/DBComponent")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string corp_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char corp_numField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int h_numField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_districtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_nodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_streetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string corp_name {
            get {
                return this.corp_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.corp_nameField, value) != true)) {
                    this.corp_nameField = value;
                    this.RaisePropertyChanged("corp_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char corp_num {
            get {
                return this.corp_numField;
            }
            set {
                if ((this.corp_numField.Equals(value) != true)) {
                    this.corp_numField = value;
                    this.RaisePropertyChanged("corp_num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int h_num {
            get {
                return this.h_numField;
            }
            set {
                if ((this.h_numField.Equals(value) != true)) {
                    this.h_numField = value;
                    this.RaisePropertyChanged("h_num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_district {
            get {
                return this.id_districtField;
            }
            set {
                if ((this.id_districtField.Equals(value) != true)) {
                    this.id_districtField = value;
                    this.RaisePropertyChanged("id_district");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_node {
            get {
                return this.id_nodeField;
            }
            set {
                if ((this.id_nodeField.Equals(value) != true)) {
                    this.id_nodeField = value;
                    this.RaisePropertyChanged("id_node");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_street {
            get {
                return this.id_streetField;
            }
            set {
                if ((this.id_streetField.Equals(value) != true)) {
                    this.id_streetField = value;
                    this.RaisePropertyChanged("id_street");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Database.IDBServer")]
    public interface IDBServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServer/getNearestPoint", ReplyAction="http://tempuri.org/IDBServer/getNearestPointResponse")]
        GoogleMapsFlashInWpf.Database.Node getNearestPoint(GoogleMapsFlashInWpf.Database.Node curr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServer/getStreets", ReplyAction="http://tempuri.org/IDBServer/getStreetsResponse")]
        GoogleMapsFlashInWpf.Database.Street[] getStreets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBServer/getNodeByAdress", ReplyAction="http://tempuri.org/IDBServer/getNodeByAdressResponse")]
        GoogleMapsFlashInWpf.Database.Node getNodeByAdress(GoogleMapsFlashInWpf.Database.Address addr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBServerChannel : GoogleMapsFlashInWpf.Database.IDBServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBServerClient : System.ServiceModel.ClientBase<GoogleMapsFlashInWpf.Database.IDBServer>, GoogleMapsFlashInWpf.Database.IDBServer {
        
        public DBServerClient() {
        }
        
        public DBServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GoogleMapsFlashInWpf.Database.Node getNearestPoint(GoogleMapsFlashInWpf.Database.Node curr) {
            return base.Channel.getNearestPoint(curr);
        }
        
        public GoogleMapsFlashInWpf.Database.Street[] getStreets() {
            return base.Channel.getStreets();
        }
        
        public GoogleMapsFlashInWpf.Database.Node getNodeByAdress(GoogleMapsFlashInWpf.Database.Address addr) {
            return base.Channel.getNodeByAdress(addr);
        }
    }
}
